name: Download and Upload MP3

on:
  workflow_dispatch:
    inputs:
      mp3_url:
        description: 'ダウンロードする MP3 の URL'
        required: true
        default: 'https://example.com/sample.mp3'

jobs:
  download_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download MP3
        run: |
          echo "Downloading MP3 from ${{ github.event.inputs.mp3_url }}..."
          curl -L "${{ github.event.inputs.mp3_url }}" --fail --show-error --output downloaded.mp3

      - name: List downloaded files
        run: ls -lh downloaded.mp3

      - name: Upload MP3 as artifact
        # ↓ v4 へアップデート
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-mp3
          path: downloaded.mp3
