# .github/workflows/download-mp3.yml
name: Download and Upload MP3

on:
  workflow_dispatch:
    inputs:
      mp3_url:
        description: 'ダウンロードする MP3 の URL'
        required: true
        default: 'https://example.com/sample.mp3'

jobs:
  download_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download MP3
        run: |
          echo "Downloading MP3 from ${{ github.event.inputs.mp3_url }}..."
          curl -L \
            -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
            -e "https://downloadx.getuploader.com/" \
            --fail --show-error \
            --output downloaded.mp3 \
            "${{ github.event.inputs.mp3_url }}"

      - name: List downloaded files
        run: ls -lh downloaded.mp3

      - name: Upload MP3 as artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-mp3
          path: downloaded.mp3
