# .github/workflows/glitch-video.yml
name: Glitch with frei0r + FFglitch

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  glitch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ffmpeg and frei0r plugins
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg frei0r-plugins

      - name: Download and extract FFglitch binary
        run: |
          wget https://ffglitch.org/pub/bin/linux64/ffglitch-0.10.2-linux-x86_64.zip -O ffglitch.zip
          unzip ffglitch.zip -d ffglitch
          chmod +x ffglitch/ffglitch

      - name: Create output directory
        run: mkdir -p processed_videos

      - name: Process videos with frei0r + FFglitch
        run: |
          for file in ./videos/*.mp4; do
            base=$(basename "$file" .mp4)
            # Step1: frei0r フィルターで色反転＋歪み
            ffmpeg -y -i "$file" \
              -vf "frei0r=invert0r:1.0,frei0r=glitch0r:0.5" \
              -c:a copy "temp_${base}.mp4"
            # Step2: FFglitch のコマンドライン版 ffgac（または ffedit）でバイナリ破壊処理
            ffglitch/ffglitch -i "temp_${base}.mp4" -o "processed_videos/${base}_ffglitch.mp4" \
              --mode random --intensity 0.7
          done

      - name: Create or update Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: glitch-v${{ github.run_number }}
          name: "Glitched Videos v${{ github.run_number }}"
          body: |
            Applied frei0r filters (invert0r, glitch0r) plus FFglitch binary distortion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload glitched videos
        uses: softprops/action-gh-release@v1
        with:
          files: processed_videos/*.mp4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
