# .github/workflows/glitch-video.yml
name: Glitch with frei0r + FFglitch

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  glitch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg frei0r-plugins unzip wget

      - name: Download and extract FFglitch
        run: |
          wget https://ffglitch.org/pub/bin/linux64/ffglitch-0.10.2-linux-x86_64.zip -O ffglitch.zip
          unzip ffglitch.zip -d ffglitch
          chmod +x ffglitch/ffglitch-0.10.2-linux-x86_64/fflive \
                    ffglitch/ffglitch-0.10.2-linux-x86_64/ffgac \
                    ffglitch/ffglitch-0.10.2-linux-x86_64/ffedit

      - name: Create output directory
        run: mkdir -p processed_videos

      - name: Process videos with frei0r + FFglitch
        run: |
          for file in ./videos/*.mp4; do
            base=$(basename "$file" .mp4)
            ffmpeg -y -i "$file" \
              -vf "frei0r=invert0r:1.0,frei0r=glitch0r:0.5" \
              -c:a copy "temp_${base}.mp4"
            ffglitch/ffglitch-0.10.2-linux-x86_64/ffgac \
              -i "temp_${base}.mp4" \
              -an \
              -mpv_flags +nopimb+forcemv \
              -qscale:v 0 \
              -g max \
              -sc_threshold max \
              -vcodec mpeg2video \
              -f rawvideo \
              -y "processed_videos/${base}_ffglitch.mp4"
          done

      - name: Create or update Release (with assets)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: glitch-v${{ github.run_number }}
          name: "Glitched Videos v${{ github.run_number }}"
          body: |
            • frei0r フィルターによる色反転＋グリッチ  
            • FFglitch(ffgac) によるモーションベクター強制 & 再エンコード
          files: processed_videos/*.mp4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
